package com.dcmc.apps.taskmanager.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PriorityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPriorityAllPropertiesEquals(Priority expected, Priority actual) {
        assertPriorityAutoGeneratedPropertiesEquals(expected, actual);
        assertPriorityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPriorityAllUpdatablePropertiesEquals(Priority expected, Priority actual) {
        assertPriorityUpdatableFieldsEquals(expected, actual);
        assertPriorityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPriorityAutoGeneratedPropertiesEquals(Priority expected, Priority actual) {
        assertThat(actual)
            .as("Verify Priority auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPriorityUpdatableFieldsEquals(Priority expected, Priority actual) {
        assertThat(actual)
            .as("Verify Priority relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPriorityUpdatableRelationshipsEquals(Priority expected, Priority actual) {
        // empty method
    }
}
